### ISSUE TITLE
Export to chat: Clear chat after export option doesn't work

### ISSUE THREAD

**Issue by horusofoz** [saif-ellafi/foundryvtt-mythic-gme#14]
The clear chat after export option shown below doesn't work.
![image](https://user-images.githubusercontent.com/3202339/161756320-25cdbc73-ae63-49c2-97f4-adce1f5c091d.png)

The content is exported but the chat is not cleared.

**Comment by saif-ellafi** [comment]
Thank you @horusofoz - fixed for next release!!
