### ISSUE TITLE
Dice so nice error in Console, Macros mostly not working

### ISSUE THREAD

**Issue by Lothex91** [saif-ellafi/foundryvtt-mythic-gme#18]
Hello! Thank you so much for your amazing work, first of all! 
That Coffee must be sum amazeeng stuff!

DiceBox.js:544 Uncaught TypeError: Cannot read properties of null (reading 'shape')
[Detected 1 package: dice-so-nice]
    at DiceBox.getVectors (DiceBox.js:544)
    at DiceBox.js:1042
    at Array.forEach (<anonymous>)
    at DiceBox.start_throw (DiceBox.js:1028)
    at Dice3D.js:600
    at Dice3D.js:433
    
Let's cut to the chase: This is the error I see in the console whenever I try - for example - to use the Random Event Macro with Dice so nice, and basically any Macro which calls for a RollTable.
What does it mean?
Is this the reason the Macros are mostly not working if I have Dice so Nice loaded?
What can I do to fix it?

**Comment by saif-ellafi** [comment]
Hi @Lothex91 - thanks. Are you using GURPS? because if so, there's a nasty issue on GURPS side

https://github.com/crnormand/gurps/issues/1414

If not, let me know! Dice so Nice is indeed supported

**Comment by Lothex91** [comment]
I am - in fact - using GURPS :(
That's unfortunate!
I read the thread you mentioned (and by the way, thank you for your quick reply!) and looks like there isn't anything I can do :(
I'll just wait until it gets fixed, I guess.
Until then, I'll have to turn off Dice so Nice.

Thank you once again for your reply and the awesome work you shared with us!

**Comment by horusofoz** [comment]
@Lothex91 Can you advise if this is still an issue?

**Comment by Lothex91** [comment]
> @Lothex91 Can you advise if this is still an issue?

Sorry but not really using Foundry at the moment, so no idea really!

**Comment by horusofoz** [comment]
@Lothex91 If you're not using the module or Foundry these days, could you close this issue?

**Comment by saif-ellafi** [comment]
@horusofoz - I am fairly sure I fixed this issue last year, it had to do with incompatibility. It is safe to close this :) Thanks!!
