### ISSUE TITLE
card setup. 

### ISSUE THREAD

**Issue by MaderDash** [saif-ellafi/foundryvtt-mythic-gme#19]
I have an issue, that all my GMA card decks are sheets. 6 cards to a sheet.
MY issue is: I can cut them with gimp, but what names do they need to be for each card, what format should I save them as? [png, Jpg .... ???] and how do I set up this folder for them?
I  would appreciate your help any way you can. Thank you for a great GMA add on, I just don't
know how to set my sheets up for this, :D 

![image_2022-07-15_195133236](https://user-images.githubusercontent.com/32471649/179327840-383bd043-e863-4fe8-bf17-c710d30d4e6d.png)

**Comment by saif-ellafi** [comment]
Hi @MaderDash - I overlooked this issue.
The cards are supposed to work with the version downloaded from DrivethruRPG, the follow the folder structure and name from there.
Here is how the folder looks, so you can follow the same pattern
![image](https://user-images.githubusercontent.com/27952699/189884501-b57072b4-0b49-4945-a1e4-cdb394138af4.png)

![image](https://user-images.githubusercontent.com/27952699/189884636-00d047ec-2358-4e46-bd97-0c4d96f2a8b6.png)
