### ISSUE TITLE
Feature Request: Tools only show up with permissions

### ISSUE THREAD

**Issue by Donixs** [saif-ellafi/foundryvtt-mythic-gme#23]
Howdy! Love the module, really fantastic and the latest update bringing the tool HUD is amazing! Something I didn't realize in the time I've used it solo till today, if you're running a group and just like using it, it'll show up on the screen for everyone. No way to close it, hide it, etc.
So I think it'd be a great feature to include a permissions setting for it, so it only shows up if you have permissions for it, so it'll work dandy for guided, co-op, or solo games! 

Thanks for reading!

**Comment by saif-ellafi** [comment]
Thanks @Donixs huge overlook from my side. Solo is not healthy for remembering about other players :D

Will resolve asap

**Comment by saif-ellafi** [comment]
Will make it so it only shows to GM players

**Comment by Donixs** [comment]
Thank you for the quick response! Would it be possible to make a setting to change the permission levels so anyone with the proper permissions can see it, not just dm? Things like co-op games were anyone would normally be able to say "Oh I'll roll a description check", and not just rely on the person hosting the game!

**Comment by saif-ellafi** [comment]
Yes, no issue there. But by default it will be only for GM roles :) will release in a moment

**Comment by saif-ellafi** [comment]
Done, released and thank you! (2.5.4)

**Comment by Donixs** [comment]
Of course, and thank you!
