### ISSUE TITLE
Chat Migration to Journal Doesn't Work (Foundry version 10 only)

### ISSUE THREAD

**Issue by gmmatt** [saif-ellafi/foundryvtt-mythic-gme#24]
I realize you probably haven't gotten to version 10 compatibility issues yet, but thought I would go ahead and submit this.

By the way - everything else seems to be working pretty well so far in v10!

**Comment by saif-ellafi** [comment]
Hi @gmmatt - this should be fixed now. Let me know if not :) Have fun

**Comment by gmmatt** [comment]
Awesome. Thanks!
