### ISSUE TITLE
undefined in chat with 2.6.1 and foundry 9

### ISSUE THREAD

**Issue by bayang** [saif-ellafi/foundryvtt-mythic-gme#25]
Hi, thanks for this module !

I'm testing in foundry v9 build 280.

When installing your module, it is the latest that is installed (2.6.1) and a warning popup appears in foundy saying that this module does not publish compatibility data or something like that (the message only appears a brief moment).
When using this version, when checking for scene alteration for example, if a random event appears and several dice rolls happen in a row, only two messages appear : an undefined one and the latest one which gets overwritten with each dice roll.

![Screenshot_20220912_214915](https://user-images.githubusercontent.com/11558944/189744053-6d7538f2-cc7b-430c-95ec-8dbb7a86f57a.png)

Here is the only error in console : 

![Screenshot_20220912_214939](https://user-images.githubusercontent.com/11558944/189744720-06cb8430-3012-4c86-91df-4cbf5b048d36.png)

I tried to uninstall and force a downgrade of your module (using a json module direct link) to version 2.5.12 (before v10 compatibility), this version works flawlessly.

![Screenshot_20220912_185721](https://user-images.githubusercontent.com/11558944/189744286-7ffe971c-dc0a-458a-a5ad-65591be24f72.png)

Is there a way when installing your module, to pin versions that are compatible ? (I don't know foundry well, I'm just beginning).
For example is user if on foundry v10, the latest module is downloaded, but if user is on v9 only 2.5.x versions are downloaded ?

Thanks again !

**Comment by saif-ellafi** [comment]
Hey @bayang - thanks for reporting this, v2.6.1 should not be possible to install in v10 :( I hope I didn't mess up

**Comment by saif-ellafi** [comment]
It is really strange that you could install v9 and 2.6.1
`  "compatibility": {
    "minimum": "10",
    "verified": "10.284",
    "maximum": "10"
  },`

**Comment by bayang** [comment]
Don't worry !
I managed to try to reinstall and be quick enough to get the error popup : 

![mythic_popup](https://user-images.githubusercontent.com/11558944/189885841-2a73633b-9508-4735-92d7-745213204922.jpg)

And here is the warning that is displayed when install is complete : 

![mythic_compat](https://user-images.githubusercontent.com/11558944/189885915-af233815-4e01-4af4-80af-bfcc58bbf4e0.png)

So for know, the workaround is to install by providing the direct link to the json module of latest 2.5.x version.

**Comment by saif-ellafi** [comment]
Thanks, alright. Yes I found the problem. Foundry should have been more explicit about this, and I didn't read the docs carefully. Will fix it, although I can't rollback on behalf of others :(

**Comment by saif-ellafi** [comment]
I have now solved this. Uninstall and re-install should give you the latest version possible for v9. Thanks for letting me know
