### ISSUE TITLE
Plans for Mythic GME v2?

### ISSUE THREAD

**Issue by lizzard77** [saif-ellafi/foundryvtt-mythic-gme#27]
Now that v2 has been published, do you have plans for integrating it into this awesome project?

**Comment by pwim** [comment]
In [2.7.0](https://github.com/saif-ellafi/foundryvtt-mythic-gme/releases/tag/2.7.0), support for this was added.

**Comment by saif-ellafi** [comment]
Indeed, thanks pwim!
