### ISSUE TITLE
Roll GM privately

### ISSUE THREAD

**Issue by onaash27** [saif-ellafi/foundryvtt-mythic-gme#29]
Please add feature to have the option to automatically get rolls for privately to GM. It helps with playing with other people, not having to switch private/public

**Comment by pwim** [comment]
This has been [added in 2.7](https://github.com/saif-ellafi/foundryvtt-mythic-gme/releases/tag/2.7.0).

**Comment by saif-ellafi** [comment]
Indeed, hope you like it!
