### ISSUE TITLE
Fate chart and scene alteration macros fail with GURPS

### ISSUE THREAD

**Issue by jonatanhedborg** [saif-ellafi/foundryvtt-mythic-gme#3]
Attached console log and screenshot of said console output

I'm running Foundry version 0.8.9.

![image](https://user-images.githubusercontent.com/124289/140584700-f44267b9-719c-41c6-80fa-66b24a9e5a24.png)
[127.0.0.1-1636150700422.log](https://github.com/saif-ellafi/foundryvtt-mythic-gme/files/7489169/127.0.0.1-1636150700422.log)

**Comment by saif-ellafi** [comment]
Hello @jonatanhedborg thank you for taking the time to come and report this issue.

Could you share a bit of context, what were you doing at the time? - Is there any modules that could be affecting Rolling Dice or Sending Dice to the Chat that could affect this module?

**Comment by jonatanhedborg** [comment]
@saif-ellafi No problems, thanks for implementing this!

I was simply trying to test it out, dragged the macros to the bar and tried them.

- I use the GURPS system (GURPS 4th ed game aid)
- I disabled all my modules except compendium folders, libwrapper (required by compendium folders) and the mythic compendium.

I will try with a different system and see if it works differently.

**Comment by jonatanhedborg** [comment]
It appears to be working in the Savage Worlds system, so it's probably some incompatibility with GURPS (I just tried creating a new, clean world in case there was something messed up in some migration, but it did not help).

**Comment by saif-ellafi** [comment]
Thank you for investigating. Will flag this for when I get some time. Could be worth while to share with GURPS people?

**Comment by mjeffw** [comment]
I am one of the coauthors of the GURPS ruleset. I have installed this module and imported the macros, but I don't see what is wrong. I can roll on any of the included roll tables without error. How do I replicate the bug?

**Comment by jonatanhedborg** [comment]
Did you try the macros?

**Comment by mjeffw** [comment]
Okay -- I see the problem now. The cause is that the GURPS system does not use the standard roll chat message. I could try to fix the immediate problem -- that the roll message data does not have a 'total' value -- but that may just reveal yet another problem. Instead of chasing them one by one, could you describe what this module is attempting to do?

**Comment by mjeffw** [comment]
Actually, I don't know what the problem is here -- it doesn't look like we're creating a custom chat message.

**Comment by saif-ellafi** [comment]
Thank you @mjeffw for looking into this. I have of course no idea about how GURPS work or your implementation, but indeed it might help for module compatibility to have standard APIs wherever possible :) best regards!

**Comment by saif-ellafi** [comment]
@mjeffw Hi there! - Not sure if there is any progress on the compatibility between this module and your system? :)

**Comment by horusofoz** [comment]
@jonatanhedborg Is this still an issue with the latest version of Mythic GME Tools?
