### ISSUE TITLE
impossible or nearly impossible doesnt work when using second edition Rulebook

### ISSUE THREAD

**Issue by Exkilter** [saif-ellafi/foundryvtt-mythic-gme#32]
I tried every chaos number and I can't do a Fate question of impossible or nearly impossible. Also when I press on the Character list it keeps creating new options called [Choose, or roll again]. I am from brazil so sorry if any there is any grammar errors. Come to Brazil ;)

**Comment by saif-ellafi** [comment]
Hi @Exkilter - Thank you. I will fix Impossible / Nearly Impossible.

Regarding the [Choose, or roll again] - there is nothing wrong in that. What is the problem you find? Do you understand the list mechanics of Mythic 2e?

**Comment by Exkilter** [comment]
I probably dont understand. Thank you for fixing the thing.
