### ISSUE TITLE
Only a single result for GME 2nd Edition Oracles

### ISSUE THREAD

**Issue by pwim** [saif-ellafi/foundryvtt-mythic-gme#33]
2.8.4 seems to have introduced a bug where Oracles like Actions only produce a single word instead of a pair (e.g. "Suffering")

**Comment by saif-ellafi** [comment]
Thanks  and sorry @pwim - the previous patch revealed an old hidden bug :) 
Double rolls on tables should be fine now in 2.8.5!

**Comment by pwim** [comment]
Awesome! Everything is working now. Looking forward to using it in my next game.

**Comment by saif-ellafi** [comment]
Yesss finally you can play! haha :) enjoy @pwim
