### ISSUE TITLE
Help Troubleshooting Foundry VTT Macro

### ISSUE THREAD

**Issue by Decanblue** [saif-ellafi/foundryvtt-mythic-gme#34]
@saif-ellafi I have loaded the files into the appropriate folder but for some reason I am receiving a 404 error when the macro looks for the cards.  It does pull the card # and if it is reversed/flipped but no image is shown.  This occurs both locally on my machine and when I use the macro on The Forge setup I have too.  The one difference on The Forge is that I cannot get the decks folder in the User Data folder so the deck data/images is only in the My Assets folder on The Forge setup.  

Can you help me figure out why the macro can't find the card images regardless of where the Foundry VTT module points to the files.  

On my local setup it is exactly as the installation instructions show and it still throws a 404 error.  The Forge and Foundry help teams noted that the applications will look for the data where it is directed so their thought is that the macro may need to be changed to account for the change in location from User Data to My Assets folder.  However, I can't seem to see where the macro might be doing that.  

Thanks for your help!

**Comment by horusofoz** [comment]
@Decanblue Have you checked that the filenames match what is expected? I had a similar issue and it came down to me having renamed the files after I downloaded them.
