### ISSUE TITLE
Issue with GMA Deck Tables

### ISSUE THREAD

**Issue by Pharmudtix** [saif-ellafi/foundryvtt-mythic-gme#44]
Not sure if this is the right place or not. 
I found an issue with the GMA Deck Tables.  The Table Results columns are missing GMA XXX VTT_part110.

**Comment by saif-ellafi** [comment]
hello @Pharmudtix - This is absolutely the right place, and sorry this took so long. You are absolutely right and will fix asap. THank you

**Comment by saif-ellafi** [comment]
Solved!
