### ISSUE TITLE
Foundry V12 Manual Roll mode not used for Fate Questions and Scene Alterations

### ISSUE THREAD

**Issue by tslays** [saif-ellafi/foundryvtt-mythic-gme#54]
I turned all my dices to manual roll mode and it works in all cases but with Fate Questions and Scene Alterations. 

In these two cases, I get the result before (!) I input the dice roll result. But it should show the result after I did input my dice roll result.

**Comment by saif-ellafi** [comment]
Thank you @tslays - good finds. Yes I feared this could happen with the changes of async dice rolling .. will check as soon as I can

**Comment by saif-ellafi** [comment]
@tslays - sorry for the delay and thanks again. fixed! Please confirm :)

**Comment by tslays** [comment]
Works now! Thanks!
