### ISSUE TITLE
Fate questions and Scene Alterations keep on giving the same answer

### ISSUE THREAD

**Issue by tslays** [saif-ellafi/foundryvtt-mythic-gme#55]
Independent from the odds and CF, it shows only "Yes!" as an answer.

**Comment by tslays** [comment]
The same is true for Scene alterations, which always result in "Scene proceeds normally!"

**Comment by saif-ellafi** [comment]
@tslays - sorry for the delay and thanks again. fixed! Please confirm :)

**Comment by tslays** [comment]
Works great! :-)

**Comment by tslays** [comment]
Works great! :-)
