### ISSUE TITLE
Support for Location Crafter (Simplified)

### ISSUE THREAD

**Issue by loofou** [saif-ellafi/foundryvtt-mythic-gme#7]
As discussed in #6 :

The Mythic Supplement "Location Crafter" is great system for creating believable and coherent randomly generated locations, areas and regions.

Afaik there are two different variations of it around: The one from the Location Crafter book and a simpler version in Mythic Magazine Vol 2 with additional material in Vol 5 and 7.

Implementation here would be a first iteration following the simplified rules in Mythic Magazine Vol 2 (and maybe 5+7), with the original full variation to be assessed later.

The focus should be on easy and fast usage during a session, regardless of solo-play or gm-based.

**Comment by saif-ellafi** [comment]
I have released a prototype for a Randomized Location Crafter Macros. For now I have decided not to include random tables.

User should ingest nested Random Tables (i.e. a Random Table as the result of another Random Table).
Progress Points are tracked like Chaos Rank, with a specific Macro for the PP-6 Equivalent

**Comment by loofou** [comment]
Point about the "Delving Deeper" - that only moves the progress counter for that specific category, not the others. The +1/-1 macros use all of them at the same time, right? So maybe a +X Category" macro makes more sense, with a little dialog in which you can specify the category and/or (only) the amount to reduce or add.

**Comment by loofou** [comment]
Also: The output should specify if it's a location, encounter or object. Encounters and Objects use the same table per default and only printing the table name can be confusing.

Otherwise this is already quite nice actually! I will experiment more with it over the next few sessions.

**Comment by saif-ellafi** [comment]
You are right, the +1/-1 are universal, but the PP-6 ones are per category! If you check the scripts inside, they allow for categories. So I see two options:
Either the macro to render a Dialog so the user chooses which category and quantity, or like now but add the +1/-1 macros for individual categories, but that could bloat a bit the list of macros.

For the outputs, yes, the output names could be corrected. The thing is, if the user names their tables differently, imho the table name should be shown. Perhaps I can add in parenthesis to which category each table was assigned to!

**Comment by saif-ellafi** [comment]
Release 2.4.1 has simplified all the PP Shift macros into a single one.
Unfortunately this is the first time I removed macros, but I think it is worth it.

**Comment by loofou** [comment]
For the Output: I think just having "Location: Tablename" would be enough.
I will check out the macro later today. Seems like a good improvement already!

**Comment by loofou** [comment]
I experimented with the system a bit more and I have to say: I quite like it! Two macros, two to three tables you can quickly create if you have the books and that's all it needs. So far I haven't encountered any bugs, but I think I have to work with it a bit longer to find some. For now, this is really great already! Thank you!

**Comment by saif-ellafi** [comment]
Thanks for coming back! Will check in the future for including the tables, but maybe first the adventure crafter next :)
